/* tslint:disable */
/* eslint-disable */
/**
 * PhotoOrganizer API
 * PhotoOrganizer image organizer
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Folder,
} from '../models/index';
import {
    FolderFromJSON,
    FolderToJSON,
} from '../models/index';

/**
 * 
 */
export class FolderControllerApi extends runtime.BaseAPI {

    /**
     * Get all folders
     */
    async getAllFoldersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Folder>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = this.configuration.apiKey("api-key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/folders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FolderFromJSON));
    }

    /**
     * Get all folders
     */
    async getAllFolders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Folder>> {
        const response = await this.getAllFoldersRaw(initOverrides);
        return await response.value();
    }

}
