logging:
  level: INFO
  loggers:
    com.example.app: DEBUG
    org.hibernate.SQL: DEBUG
    org.reflections: ERROR

EsConfiguration:
  clusterName: elasticsearch
  servers:
    - 10.109.186.194:9200
  settings:
    node.name: photoapi-client
    node.data: false
    node.ingest: false
    node.master: false
    path.home: /tmp
    discovery.seed_hosts: 10.109.186.194
