elastic:
    hostAndPort: dockerhost.stapledon.local:9200

spring:
    application:
        name: PhotoOrganizer
    cloud:
        gcp:
            project-id: speedy-emissary-344223
            credentials:
                location: file:.//speedy-emissary-344223-ac439d946b21.json

management:
    endpoint:
        health:
            show-details: "ALWAYS"
            sensitive: false
        info:
            env:
                enabled: true
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include:
                    - health
                    - metrics
                    - info
    health:
        elasticsearch:
            enabled: false
