elastic:
    hostAndPort: dockerhost.stapledon.ca:9200
    password: day@force

spring:
    application:
        name: PhotoOrganizer
    cloud:
        gcp:
            project-id: speedy-emissary-344223
            credentials:
                location: classpath:speedy-emissary-344223-ac439d946b21.json

management:
    endpoint:
        health:
            show-details: "ALWAYS"
            sensitive: false
        info:
            env:
                enabled: true
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include:
                    - health
                    - metrics
                    - info
    health:
        elasticsearch:
            enabled: false

organizer:
    tidyup:
        verbose: true
        is-copy: false
        dry-run: false
    takeout:
        exports: /vault/Google Exports/Unsorted-Live
    destination:
        base-path: /vault/Google Exports/Sorted
